import os
WD=os.environ.get("GKPI_WORKDIR","/tmp/generic-kpi")
#!/usr/bin/env python3
"""Build the 📕 How to Use (Directions) and 📖 Definitions & Sources tabs, and final polish."""
import json
import wb
from wb import (col, NAVY, BLUE, GREEN, GRAY, YELLOW, WHITE, LTGRAY, rgb,
                CUR, INT, PCT, PCTS, DATEF)

st=json.load(open(f"{WD}/state.json"))
SID=st["SID"]; G=st["G"]; SR=st["SR"]; R0=st["R0"]; RN=st["RN"]
LASTL=st["LASTL"]
D=json.load(open(f"{WD}/data.json")); COMPANY=D["company"]; SEED=D["seed"]; NC=len(D["customers"])
CM="'Customers — MRR'"
vals=[]; reqs=[]
def V(t,a1,m): vals.append({"range":f"'{t}'!{a1}","values":m})

# =====================================================================
# 📕 How to Use
# =====================================================================
T="📕 How to Use"; g=G[T]
rowsA=[]
def line(text): rowsA.append([text])
line(f"📕 {COMPANY} — SaaS KPI Dashboard  ·  How to Use")           # 1 title
line("")                                                            # 2
line("WHAT THIS IS")                                                # 3 banner
line("A one-workbook operating dashboard for a subscription (SaaS) business: recurring revenue (MRR/ARR), "
     "usage (Monthly Active Users), retention, cash collection, and per-customer detail. "
     "Everything you see is FICTIONAL sample data — made-up company names and numbers — so it can be shared publicly.")
line("")
line("WHERE TO START")                                              # 6 banner
line("① 📊 Combined Summary — the one-screen snapshot (start here).   ② 📊 Revenue Dashboard & 📊 Usage Summary — the detail behind it.   "
     "③ 🔍 Compare — pick any metric and two months to see the change.   ④ The 'Customers —' and 'Usage —' tabs are the raw data everything is built from.")
line("")
line("TAB GUIDE")                                                   # 9 banner
tab_start=len(rowsA)+1  # 1-based row where table header goes
guide=[
 ("📊 Combined Summary","One-screen exec snapshot — revenue (accrual + cash), usage, autopay."),
 ("🔍 Compare","Pick any metric + two periods; see the delta and % change."),
 ("📊 Revenue Dashboard","Headline revenue KPIs with month-over-month change, movers, new/churned."),
 ("📊 MRR & ARR Summary","Monthly revenue cascade: ARR → discounts → net → net retention (NRR)."),
 ("📊 Usage Summary","MAU this month, customers over their usage minimum, seats, active users."),
 ("📉 Churn & New Revenue","MRR bridge — starting + new − churned ± expansion = ending."),
 ("💳 Autopay Collections","Recurring revenue collected on autopay, net of discounts."),
 ("💵 Revenue → Cash","Cascade from accrual revenue → invoiced → cash collected."),
 ("⏱ Collections & A/R","Accounts-receivable aging and on-time collection rate."),
 ("💵 Invoiced Volume","Monthly cash-out schedule (quarterly billers land as lumps)."),
 ("📈 Usage Monthly History","Total MAU / seats / active users over time."),
 ("Over-Min History","Share of customers over their MAU minimum, over time."),
 ("Customers — MRR / ARR","Data layer: one row per customer, one column per month."),
 ("Usage — MAU / Seats / Active Users per Customer","Data layer: per-customer monthly usage."),
 ("Minimum MAU","Each customer's contracted usage floor (drives over/under-min)."),
 ("Pricing Engine","Illustrative per-customer pricing model."),
 ("📖 Definitions & Sources","Every metric defined, with where each number comes from."),
]
line("Tab")  # placeholder (overwritten by table below)
for _ in guide: line("")
line("")
flow_row=len(rowsA)+1
line("HOW THE NUMBERS FLOW")                                        # banner
line("The 'Customers —' and 'Usage —' tabs are the single source of data: one row per customer, one column per month. "
     "Every dashboard is built with formulas that read from those tabs — so if you change a number in the data layer, "
     "every summary, chart, and comparison updates automatically. Nothing in this workbook links to any external file or real system.")
line("")
line("USING IT WITH YOUR OWN DATA (paste your reports)")            # banner
line("To use this as YOUR dashboard: (1) On the ⏱ Collections & A/R tab, paste your A/R Aging report and your "
     "payments/collections report into the two yellow paste areas — Total A/R, the aging buckets, and the on-time "
     "collection rate compute automatically (and flow to the Combined Summary). (2) On the input tabs 'Customers — MRR' "
     "and 'Usage — MAU/Seats/Active Users', replace the sample rows with your own per-customer numbers by month — every "
     "dashboard (revenue, ARR, retention, usage, churn, autopay) recalculates. Also set each customer's floor on 'Minimum MAU'. "
     "You never edit the dashboard tabs directly — they're all formulas.")
line("")
line("HOW TO REFRESH WITH NEW SAMPLE DATA")                         # banner
line(f"This workbook was generated by a small script from a random seed (seed={SEED}, {NC} customers). "
     "To spin up a brand-new standalone copy with different fictional numbers, re-run the generator "
     "(the /generic-kpi skill in Claude). It creates a fresh Google Sheet and returns a shareable link — nothing is overwritten.")
line("")
line("⚠️  DISCLAIMER — All company names, customers, and figures in this workbook are fictional and for illustration only.")
V(T,"A1",[[r[0]] for r in rowsA])
# lay the tab-guide table into two columns starting at the 'Tab' placeholder row
V(T,f"A{tab_start}",[["Tab","What it shows"]])
V(T,f"A{tab_start+1}",[[a,b] for a,b in guide])

# formatting
reqs+=[wb.colwidth(g,0,1,430),wb.colwidth(g,1,2,430),
       wb.merge(g,0,1,0,2), wb.cellfmt(g,0,1,0,2,bg=NAVY,bold=True,fg=WHITE,size=15,valign="MIDDLE"),
       wb.cellfmt(g,0,300,0,2,wrap="WRAP"),
       wb.tabcolor(g,rgb(0.95,0.77,0.06))]
# banner rows (0-based): WHAT(2),WHERE(5),TABGUIDE(8),FLOW,REFRESH,DISCLAIMER
for label in ["WHAT THIS IS","WHERE TO START","TAB GUIDE","HOW THE NUMBERS FLOW","USING IT WITH YOUR OWN DATA (paste your reports)","HOW TO REFRESH WITH NEW SAMPLE DATA"]:
    idx=[i for i,r in enumerate(rowsA) if r[0]==label][0]
    reqs.append(wb.merge(g,idx,idx+1,0,2))
    reqs.append(wb.cellfmt(g,idx,idx+1,0,2,bg=BLUE,bold=True,fg=WHITE,size=12,valign="MIDDLE"))
# tab-guide header + body styling
reqs.append(wb.cellfmt(g,tab_start-1,tab_start,0,2,bg=GRAY,bold=True))
reqs.append(wb.cellfmt(g,tab_start,tab_start+len(guide),0,1,bold=True))
# disclaimer emphasis
didx=[i for i,r in enumerate(rowsA) if r[0].startswith("⚠️")][0]
reqs.append(wb.cellfmt(g,didx,didx+1,0,2,bg=YELLOW,bold=True,italic=True))
reqs.append(wb.freeze(g,rows=1))
print("prepared How to Use")

# =====================================================================
# 📖 Definitions & Sources
# =====================================================================
T="📖 Definitions & Sources"; g=G[T]
V(T,"A1",[[f"📖 {COMPANY} — Definitions & Sources  (data dictionary)"]])
V(T,"A2",[["Metric","Definition","Current value (live)","Where it comes from"]])
CS="'📊 Combined Summary'"; MS="'📊 MRR & ARR Summary'"; US="'📊 Usage Summary'"
defs=[
 ("Gross MRR","Monthly recurring revenue at list price, every customer counted monthly regardless of billing term.",
    f"={CS}!B5",f"{CM} summary row {SR['GROSS']}"),
 ("Discounts (mo)","Total contractual discounts applied this month.",f"=-{CS}!B6",f"{CM} row {SR['DISC']}"),
 ("Net MRR ⭐","Gross MRR − discounts. The headline recurring number (board metric). Quarterly billers still counted at monthly run-rate.",
    f"={CS}!B7",f"{CM} row {SR['NET']}"),
 ("Total ARR (gross)","Gross MRR × 12 — contracted annual run-rate at list price.",f"={CS}!B8",f"{CM} row {SR['ARR']}"),
 ("Net ARR","Net MRR × 12 — annual run-rate after discounts.",f"={CS}!B9",f"{CM} row {SR['NET']} × 12"),
 ("MoM ARR Growth %","This month's ARR ÷ last month's ARR − 1.",f"={CS}!B10",f"{CM} row {SR['GROW']}"),
 ("Paying Customers","Count of customers with MRR > 0 this month.",f"={CS}!B11",f"{CM} row {SR['PAY']}"),
 ("Net Invoiced (timing)","What is actually invoiced this month: quarterly billers appear only in their Q-start month (3×). Differs from Net MRR by billing timing only.",
    f"={CS}!B14",f"{CM} row {SR['INV']}"),
 ("Net Retention (NRR)","Cur-month MRR ÷ prior-period MRR for customers that existed then (excludes new logos). Shown MoM and trailing-12-month.",
    f"={MS}!I3",f"{MS} cols I / J"),
 ("New Customer ARR","Annualized net MRR from customers whose revenue start date is this month.",f"={MS}!H3",f"{MS} col H"),
 ("Total MAU","Monthly Active Users across all customers this month — the usage / billing driver.",f"={US}!B3",
    "'Usage — MAU per Customer' TOTAL row"),
 ("MoM MAU Growth %","This month's MAU ÷ last month's MAU − 1.",f"={US}!B5","'Usage — MAU per Customer'"),
 ("Customers over MAU Min","Customers whose MAU ≥ their contracted minimum.",f"={US}!E3","'Minimum MAU'"),
 ("% over MAU Min","Share of paying customers over their minimum.",f"={US}!E4","'Minimum MAU' ÷ paying"),
 ("Total Seats","Licensed seats across customers.",f"={US}!E6","'Usage — Seats per Customer'"),
 ("Total Active Users","Users who logged in this month.",f"={US}!B7","'Usage — Active Users per Customer'"),
 ("Autopay MRR","Gross MRR from customers on autopay.",f"={CS}!B30","'💳 Autopay Collections'"),
 ("Cash Collected","Cash actually received (modeled ≈88% of invoiced, prior closed month).",f"={CS}!B16","'💵 Revenue → Cash'"),
 ("Total A/R","Open accounts-receivable at period end (modeled aging).",f"={CS}!B17","'⏱ Collections & A/R'"),
]
V(T,"A3",[[a,b,c,d] for a,b,c,d in defs])
reqs+=[wb.colwidth(g,0,1,170),wb.colwidth(g,1,2,430),wb.colwidth(g,2,3,140),wb.colwidth(g,3,4,300),
       wb.cellfmt(g,2,2+len(defs),0,4,bg=WHITE),   # clean white bg (no green highlight)
       wb.merge(g,0,1,0,4), wb.cellfmt(g,0,1,0,4,bg=NAVY,bold=True,fg=WHITE,size=14,valign="MIDDLE"),
       wb.cellfmt(g,1,2,0,4,bg=BLUE,bold=True,fg=WHITE,halign="CENTER"),
       wb.cellfmt(g,2,2+len(defs),0,1,bold=True),
       wb.cellfmt(g,2,2+len(defs),1,2,wrap="WRAP",size=9),
       wb.cellfmt(g,2,2+len(defs),2,3,bold=True,halign="RIGHT"),
       wb.cellfmt(g,2,2+len(defs),3,4,wrap="WRAP",size=9,italic=True,fg=rgb(0.4,0.4,0.4)),
       wb.freeze(g,rows=2), wb.tabcolor(g,rgb(0.29,0.53,0.91))]
# (Net MRR green highlight removed per request)
print("prepared Definitions")

# =====================================================================
# hide raw data-layer tabs' neighbors? keep visible. Hide the 🧭 nothing.
# Order tabs: How to Use first.
# =====================================================================
order=["📕 How to Use","📖 Definitions & Sources","📊 Combined Summary","🔍 Compare",
       "📊 Revenue Dashboard","📊 MRR & ARR Summary","📊 Usage Summary","📉 Churn & New Revenue",
       "💳 Autopay Collections","💵 Revenue → Cash","⏱ Collections & A/R","💵 Invoiced Volume",
       "📈 Usage Monthly History","Over-Min History","Customers — MRR","Customers — ARR",
       "Usage — MAU per Customer","Usage — Seats per Customer","Usage — Active Users per Customer",
       "Minimum MAU","Pricing Engine"]
for i,t in enumerate(order):
    if t in G:
        reqs.append({"updateSheetProperties":{"properties":{"sheetId":G[t],"index":i},"fields":"index"}})

print("Writing values (docs)...")
wb.set_values(SID, vals)
print("Applying formats (docs)...")
wb.batch(SID, reqs)
print("DONE docs + ordering")
